name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Build examples
      run: |
          make -C guest
          cargo build --verbose --examples
    - name: Run tests
      run: cargo test --verbose
    - name: Generate doc
      run: |
          cargo doc --no-deps
          echo "<meta http-equiv=\"Refresh\" content=\"0; url='kvm_rs/index.html'\"/>" > target/doc/index.html
    - name: Upload doc to gh pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./target/doc
